config/routes.rb
Rails.application.routes.draw do

  unauthenticated do
    devise_scope :user do
      root to: "devise/sessions#new", :as => 'unauthenticated_user_root'
    end
  end

  devise_for :users, controllers: { registrations: "users/registrations" }

  patch "users/accept_invite"=>"users#accept_invite", as: :accept_invite

  authenticate :user do
    root to: "dashboards#show", :as => 'authenticated_user_root'

    resources :invitations, only: [:new, :create]

    get 'profile'=>'profiles#edit', as: :myprofile
    patch 'profile'=>'profiles#update'

    get 'metrics'=>'metrics#show', as: :metrics
    resources :users, only: [:index]

    resources :channels, only: [:update, :create, :destroy] do
      resources :tickets, module: 'channels' do
        post 'new_comment'
      end

      namespace :tickets, module: 'channels' do
        put ':id/approve'=>'tickets#approve', as: :approve
        put ':id/reprove'=>'tickets#reprove', as: :reprove
        put ':id/done'=>'tickets#done', as: :done
        put ':id/cancel'=>'tickets#cancel', as: :cancel
      end

      resources :members, defaults: { format: :json }, only: [:create, :destroy], module: 'channels'
    end

    resources :tickets, only: [] do
      post :assign_to, on: :member
    end

    get 'tickets/:id/download'=>'tickets#download', as: :ticket_attachment_download
    get 'comments/:id/download'=>'comments#download', as: :comment_attachment_download

    resources :groups, only: [:new, :create, :show] do
      member do
        post 'add_user'
        delete 'inactivate_member'
        post 'add_channel'
      end
    end

    resource :dashboard, only: [:show]
  end

  if Rails.env.development?
    mount MailPreview => 'mail_preview'
  end
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  include Notifiable
  validates :name, uniqueness: true, presence: true
  has_many :channel_members, dependent: :destroy
  has_many :members, through: :channel_members
  has_many :tickets
  has_many :group_channels
  has_many :groups, through: :group_channels

  scope :user_scope, -> (user) {
    if user.client? and user.group.present?
      user.group.channels
    else
      all
    end
  }

  def new_member(user)
    members << user
    user
  end

  def name_with_hashtag
    "##{name}"
  end

  def add_ticket(ticket)
    tickets << ticket
    ticket
  end
end

app/controllers/channels/members_controller.rb
class Channels::MembersController < ApplicationController
  before_action :set_channel
  before_action :set_user, only: [:create]
  respond_to :json

  def create
    @channel_member = @channel.new_member(@user)
    respond_with(@channel, member: @user)
  end

  def destroy
    ChannelMember.destroy params[:id]
  end

  private

    def set_channel
      @channel = Channel.find params[:channel_id]
    end

    def set_user
      @user = User.find params[:user_id]
    end
end

app/controllers/channels/tickets_controller.rb
class Channels::TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy,
                                    :approve, :reprove, :done, :cancel]
  before_action :set_channel
  after_action :verify_authorized, except: [:show, :new_comment]
  respond_to :html, :json

  # GET /tickets
  def index
    authorize @channel, :show?
    @tickets = TicketPolicy::Scope.new(current_user, @channel.tickets).
      resolve.
      default_search(params[:search], params[:status]).
      page(params[:page]).per(params[:per] || 200)
    respond_with(@channel, @tickets)
  end

  # GET /tickets/1
  def show
    authorize @ticket, :show?

    if @ticket.unread? and !current_user.client?
      @ticket.in_progress!
      @ticket.update attended_at: DateTime.current
    end
    respond_with(@channel, @ticket)
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
    authorize @ticket
    respond_with(@channel, @ticket)
  end

  # GET /tickets/1/edit
  def edit
    authorize @ticket
    respond_with(@channel, @ticket)
  end

  # POST /tickets
  def create
    authorize Ticket
    @ticket = Ticket.new(ticket_params)
    @ticket.channel = @channel
    @ticket.created_by = current_user
    if @ticket.save
      Notification.create(notifiable: @ticket, created_by: current_user,
                          action: :created).deliver
    end
    respond_with(@channel, @ticket)
  end

  # PATCH/PUT /tickets/1
  def update
    authorize @ticket
    @ticket.update(ticket_params)
    respond_with(@channel, @ticket)
  end

  # DELETE /tickets/1
  def destroy
    authorize @ticket
    @ticket.destroy
    respond_with(@channel, @ticket)
  end

  def approve
    authorize @ticket
    if @ticket.approved_by(current_user)
      head 204
    else
      render json: I18n.t('notification.server.internal_error').to_json, status: :internal_server_error
    end
  end

  def reprove
    authorize @ticket
    if @ticket.reproved_by(current_user)
      head 204
    else
      render json: I18n.t('notification.server.internal_error').to_json, status: :internal_server_error
    end
  end

  def done
    authorize @ticket
    if @ticket.done_by(current_user)
      head 204
    else
      render json: I18n.t('notification.server.internal_error').to_json, status: :internal_server_error
    end
  end

  def cancel
    authorize @ticket
    if @ticket.cancelled_by(current_user, params[:reason])
      head 204
    else
      render json: I18n.t('notifications.ticket.errors.cancel').to_json, status: :unprocessable_entity
    end
  end

  def new_comment
    @ticket = Ticket.find(params[:ticket_id])
    if @ticket.update(params_new_comment)
      send_comment_notification
    end

    redirect_to channel_ticket_path(channel_id: @channel, id: @ticket)
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def set_channel
    @channel = Channel.find params[:channel_id]
  end

  def send_comment_notification
    emails = if @ticket.comments.last.author.client?
      User.attendant.pluck(:email)
    else
      [@ticket.created_by.email]
    end
    CommentNotificationMailer.notify(emails, @ticket.comments.last).deliver
  end

  # Only allow a trusted parameter "white list" through.
  def ticket_params
    params.require(:ticket).permit(:subject, :content, :is_priority,
                                   :estimated_time, :assign_to_id, :complexity, :attachment)
  end

  def params_new_comment
    params.require(:ticket).permit(comments_attributes: [:content, :attachment]).tap do |whitelisted|
      whitelisted[:comments_attributes]['0'][:author_id] = current_user.id
    end
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  # GET /channels
  def index
    @channels = Channel.all
    authorize(@channels)
    respond_with(@channels)
  end

  # GET /channels/1
  def show
    authorize(@channel)
    respond_with(@channel)
  end

  # GET /channels/new
  def new
    @channel = Channel.new
    authorize(@channel)
    respond_with(@channel)
  end

  # GET /channels/1/edit
  def edit
    authorize(@channel)
    respond_with(@channel)
  end

  # POST /channels
  def create
    @channel = Channel.new(channel_params)
    authorize(@channel)

    @channel.save
    respond_with(@channel) do |format|
      if @channel.persisted?
        format.html { redirect_to channel_tickets_path(@channel) }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /channels/1
  def update
    authorize(@channel)
    @channel.update(channel_params)
    respond_with(@channel)
  end

  # DELETE /channels/1
  def destroy
    @channel.destroy
    authorize(@channel)
    respond_with(@channel)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def channel_params
      params.require(:channel).permit(:name, :purpose, member_ids: [])
    end
end

app/views/channels/_form.html.erb
<%= form_for(@channel) do |f| %>
  <% if @channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% @channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, I18n.t('channel.form.label.name') %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :purpose, I18n.t('channel.form.label.purpose') %><br>
    <%= f.text_field :purpose %>
  </div>
  <div class="field">
    <%= f.select :member_ids, User.client.collect { |user| [ user.email, user.id ] }, {}, { multiple: true } %><br>
  </div>
  <div class="actions">
    <%= f.submit I18n.t('channel.button.create') %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing channel</h1>

<%= render 'form' %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<h1>Listing channels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Purpose</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @channels.each do |channel| %>
      <tr>
        <td><%= channel.name %></td>
        <td><%= channel.purpose %></td>
        <td><%= link_to 'Show', channel %></td>
        <td><%= link_to 'Edit', edit_channel_path(channel) %></td>
        <td><%= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Channel', new_channel_path %>

app/views/channels/new.html.erb
<h1>New channel</h1>

<%= render 'form' %>

<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @channel.name %>
</p>

<p>
  <strong>Purpose:</strong>
  <%= @channel.purpose %>
</p>

<%= link_to 'Adicionar ticket', new_channel_ticket_path(@channel)  %>

<%= link_to 'Edit', edit_channel_path(@channel) %> |
<%= link_to 'Back', channels_path %>