config/routes.rb
Rails.application.routes.draw do

  unauthenticated do
    devise_scope :user do
      root to: "devise/sessions#new", :as => 'unauthenticated_user_root'
    end
  end

  devise_for :users, controllers: { registrations: "users/registrations" }

  patch "users/accept_invite"=>"users#accept_invite", as: :accept_invite

  authenticate :user do
    root to: "dashboards#show", :as => 'authenticated_user_root'

    resources :invitations, only: [:new, :create]

    get 'profile'=>'profiles#edit', as: :myprofile
    patch 'profile'=>'profiles#update'

    get 'metrics'=>'metrics#show', as: :metrics
    resources :users, only: [:index]

    resources :channels, only: [:update, :create, :destroy] do
      resources :tickets, module: 'channels' do
        post 'new_comment'
      end

      namespace :tickets, module: 'channels' do
        put ':id/approve'=>'tickets#approve', as: :approve
        put ':id/reprove'=>'tickets#reprove', as: :reprove
        put ':id/done'=>'tickets#done', as: :done
        put ':id/cancel'=>'tickets#cancel', as: :cancel
      end

      resources :members, defaults: { format: :json }, only: [:create, :destroy], module: 'channels'
    end

    resources :tickets, only: [] do
      post :assign_to, on: :member
    end

    get 'tickets/:id/download'=>'tickets#download', as: :ticket_attachment_download
    get 'comments/:id/download'=>'comments#download', as: :comment_attachment_download

    resources :groups, only: [:new, :create, :show] do
      member do
        post 'add_user'
        delete 'inactivate_member'
        post 'add_channel'
      end
    end

    resource :dashboard, only: [:show]
  end

  if Rails.env.development?
    mount MailPreview => 'mail_preview'
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :members, class: User

  has_many :group_channels
  has_many :channels, through: :group_channels

  scope :user_scope, -> (user) {
    if user.client?
      user.group
    else
      all
    end
  }

  def invite(email, inviter)
    Invitation.invite(email: email, sender: inviter,
                      group_id: self.id, user_type: :client)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  respond_to :html, :json

  def new
    @group = Group.new
    authorize @group
    respond_with(@group)
  end

  def update
    @group = Group.find(params[:id])
    authorize @group
    @group.update(group_params)
    respond_with(@group)
  end

  def create
    @group = Group.create(group_params)
    authorize @group
    respond_with(@group)
  end

  def show
    @group = Group.find(params[:id])
    authorize @group
    respond_with(@group)
  end

  def add_user
    @group = Group.find(params[:id])
    authorize @group, :update?
    
    if @group.invite(params[:email], current_user)
      render invite_user_with_success_message(params[:email])
    else
      render invited_user_error_message(params[:email])
    end
  end

  def inactivate_member
    @group = Group.find(params[:id])
    authorize @group, :edit?
    @user = User.find params[:member_id]
    @user.inactive!
    render :json=>@user.to_json
  end

  def add_channel
    @group = Group.find(params[:id])
    authorize @group, :update?
    unless @group.channel_ids.include? params[:channel_id]
      @group.channels << Channel.find(params[:channel_id])
    end
    respond_with(@group)
  end

  private

  def group_params
    params.require(:group).permit(:name, :purpose, member_ids: [],
                                  channel_ids: [])
  end

  def invite_user_with_success_message(email)
    {  text: t('invitation.flash_messages.success', email: email) }
  end

  def invited_user_error_message(email)
    { text: I18n.t('invitation.flash_messages.invited_user', email: email) }
  end
end

app/views/groups/new.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, I18n.t('group.form.label.name') %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :purpose, I18n.t('group.form.label.purpose') %><br>
    <%= f.text_field :purpose %>
  </div>

  <div class="field">
    <%= f.select :member_ids, User.client.all.collect { |user| [user.email, user.id] }, {}, {multiple: true} %>
  </div>

  <div class="field">
    <%= f.select :channel_ids, Channel.all.collect { |channel| [channel.name, channel.id] }, {}, {multiple: true} %>
  </div>

  <div class="actions">
    <%= f.submit I18n.t('group.form.button.create') %>
  </div>
<% end %>

app/views/groups/show.html.erb
<h1><%= @group.name %></h1>
<p><em><%= @group.purpose %></em></p>

<template id="add-user-popover">
  <div class="flashes">
    <div class="alert alert-success" style="display: none"></div>
    <div class="alert alert-danger" style="display: none"></div>
  </div>
  <div class="form-group">
    <%= text_field_tag 'member_id', nil,
      { class: 'form-control user-add-field', placeholder: "Email" }  %>
  </div>
  <%= button_tag t('group.links.add_member'),
    class: 'btn btn-default',
    id:    'add-client-button',
    data:  { url: add_user_group_path(@group) } %>
</template>

<template id="add-channel-popover">
  <div class="flashes">
    <div class="alert alert-success" style="display: none"></div>
    <div class="alert alert-danger" style="display: none"></div>
  </div>
  <div class="form-group">
    <%= collection_select nil, :channel_id,
      Channel.user_scope(current_user).where.not(id: @group.channel_ids),
      :id, :name, {}, class: 'form-control channel-add-field' %>
  </div>
  <%= button_tag t('group.links.add_channel'), class: 'btn btn-default',
    data: { 'add-channel-button' => true, url: add_channel_group_path(@group) } %>
</template>

<h3>
  Canais
  <% if policy(@group).update? %>
    <a
       class="add-channel"
       id="add-channel"
       data-html="true"
       data-toggle="popover"
       data-title="Adicionar canal"
       data-content-target="#add-channel-popover">
      Adicionar canal
    </a>
  <% end %>
</h3>
<p class="group-channels">
  <% @group.channels.each do |channel| %>
    <%= link_to channel_tickets_path(channel) do %>
      <span class="prefix">#</span><%= channel.name %>
    <% end %>
  <% end %>
</p>

<h3>Usuários</h3>
<div id="error"></div>
<div class="row users">
  <% @group.members.each do |user| %>
    <div class="col-md-4 col-sm-6 col-lg-3 col-xs-12">
      <div class="user <%= 'inactive' if user.inactive? or user.pending? %>" data-user-id="<%= user.id %>">
        <div class="img">
          <%= image_tag user.avatar.url(:square), class: 'img-circle thumb' %>
        </div>
        <div class="info">
          <div class="truncate"><strong><%= user.email %></strong></div>
          <div class="truncate"><em><%= user.name %></em></div>
          <% if user.pending? %>
            <div><em>Pendente</em></div>
          <% end %>
          <% if user.active? %>
          <%= link_to icon(:trash), inactivate_member_group_path(@group, member_id: user.id),
              data: { 'behaviour' => 'delete-member', 'method'=>:delete,
              'confirm' => 'Tem certeza?', 'remote'=>true },
              class: 'delete-user icon' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <% if policy(@group).update? %>
   <div class="col-sm-2 col-xs-12">
      <div class="add-user-box">
        <center>
          <a
             class="add-user"
             data-html="true"
             data-toggle="popover"
             data-title="Adicionar usuário"
             data-content-target="#add-user-popover">
            <%= icon :plus %>
          </a>
        </center>
      </div>
    </div>
    <% end %>
</div>