config/routes.rb
Rails.application.routes.draw do

  unauthenticated do
    devise_scope :user do
      root to: "devise/sessions#new", :as => 'unauthenticated_user_root'
    end
  end

  devise_for :users, controllers: { registrations: "users/registrations" }

  patch "users/accept_invite"=>"users#accept_invite", as: :accept_invite

  authenticate :user do
    root to: "dashboards#show", :as => 'authenticated_user_root'

    resources :invitations, only: [:new, :create]

    get 'profile'=>'profiles#edit', as: :myprofile
    patch 'profile'=>'profiles#update'

    get 'metrics'=>'metrics#show', as: :metrics
    resources :users, only: [:index]

    resources :channels, only: [:update, :create, :destroy] do
      resources :tickets, module: 'channels' do
        post 'new_comment'
      end

      namespace :tickets, module: 'channels' do
        put ':id/approve'=>'tickets#approve', as: :approve
        put ':id/reprove'=>'tickets#reprove', as: :reprove
        put ':id/done'=>'tickets#done', as: :done
        put ':id/cancel'=>'tickets#cancel', as: :cancel
      end

      resources :members, defaults: { format: :json }, only: [:create, :destroy], module: 'channels'
    end

    resources :tickets, only: [] do
      post :assign_to, on: :member
    end

    get 'tickets/:id/download'=>'tickets#download', as: :ticket_attachment_download
    get 'comments/:id/download'=>'comments#download', as: :comment_attachment_download

    resources :groups, only: [:new, :create, :show] do
      member do
        post 'add_user'
        delete 'inactivate_member'
        post 'add_channel'
      end
    end

    resource :dashboard, only: [:show]
  end

  if Rails.env.development?
    mount MailPreview => 'mail_preview'
  end
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  include Notifiable
  validates :name, uniqueness: true, presence: true
  has_many :channel_members, dependent: :destroy
  has_many :members, through: :channel_members
  has_many :tickets
  has_many :group_channels
  has_many :groups, through: :group_channels

  scope :user_scope, -> (user) {
    if user.client? and user.group.present?
      user.group.channels
    else
      all
    end
  }

  def new_member(user)
    members << user
    user
  end

  def name_with_hashtag
    "##{name}"
  end

  def add_ticket(ticket)
    tickets << ticket
    ticket
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  include Notifiable
  include PgSearch

  pg_search_scope :search_full_text, :against => {
    :subject => 'A',
    :content => 'C'
  },
  :associated_against => {
    :created_by => { :email => 'B', name: 'B' }
  },
  :ignoring => :accents, :using => [:tsearch, :trigram, :dmetaphone]

  belongs_to :created_by, class: User
  belongs_to :assign_to, class: User
  belongs_to :channel

  has_many :comments
  accepts_nested_attributes_for :comments

  validates_presence_of :subject
  validates_presence_of :content
  validates_presence_of :created_by, associated: true
  validates_length_of :subject, maximum: 254

  enum status: [:unread, :reproved, :in_progress, :done, :approved, :canceled]

  has_attached_file :attachment, styles: {
    thumb: '100x100#'
  }, :size => { :in => 0..25.megabytes }, :s3_permissions => :private

  validates_attachment_content_type :attachment, :content_type => [/\Aimage\/.*\Z/, /\Aapplication\/.*\Z/, /\Atext\/.*\Z/]

  recipients_for(:created) { User.attendant }
  recipients_for(:approved) { [assign_to] }
  recipients_for(:reproved) { [assign_to] }
  recipients_for(:done) { [created_by] }
  recipients_for(:canceled) { [created_by] }
  recipients_for(:assigned) { [assign_to] }

  context_for :created, :default_notification_context
  context_for :approved, :default_notification_context
  context_for :reproved, :default_notification_context
  context_for :done, :default_notification_context
  context_for :canceled, :default_notification_context
  context_for :assigned, :default_notification_context

  scope :solved, -> { where.not(resolved_at: nil) }
  scope :attended, -> { where.not(attended_at: nil) }

  scope :user_scope, -> (user) {
    if user.client?
      where(created_by: user.siblings.to_a)
    else
      all
    end
  }

  scope :default_search, -> (search, status=nil) {
    unless status.present?
      query_statuses = [statuses[:unread], statuses[:reproved],
        statuses[:in_progress], statuses[:done]]
    else
      query_statuses = statuses[status.to_sym]
    end
    query = where(status: query_statuses)

    if search.present?
      query.search_full_text(search)
    else
      query
    end
  }

  scope :apply_sort, -> {
    all.sort_by do |o|
      [Ticket.statuses[o.status], (o.is_priority ? -1 : 1),
        -o.sla, o.updated_at, o.subject]
    end
  }

  scope :recently_first, -> {
    order :updated_at=>:desc
  }

  scope :latest, -> {
    where(created_at: 1.month.ago)
  }

  after_find :auto_approve!

  def auto_approve!
    TicketAutoApproval.new(self).auto_approve!
  end

  def old?
    (updated_at - 15.days.ago) < 0
  end

  def default_notification_context
    {
      ticket: subject,
      channel: channel.try(:name_with_hashtag),
      assigned_to: assign_to.try(:email)
    }
  end

  def self.statuses_color
    #TODO: transfer to yml
    {
      :unread=>'#b0d8dd',
      :in_progress=>'#1674b3',
      :done=>'#ffca16',
      :approved=>'#298d10',
      :reproved=>'#b31200',
      :canceled=>'#420000'
    }.with_indifferent_access
  end

  def sla_points
    5 #TODO: configurable
  end

  def hours_taken
    resolved_at = self.resolved_at || DateTime.current.to_time
    (created_at.business_time_until(resolved_at) / 1.hour).ceil
  end

  def sla
    if canceled?
      return 0
    end

    if exceeded_estimation?
      sla_points
    else
      (sla_points*(hours_taken/estimated_time.to_f)).ceil
    end
  end

  def estimated_time
    super || 4 #TODO: Make it configurable
  end

  def exceeded_estimation?
    hours_taken >= estimated_time
  end

  def status_humanized
    Ticket.humanize_status(status)
  end

  def self.humanize_status(status)
    I18n.translate("ticket.statuses.#{status}")
  end

  def approved_by(user)
    approved!
    Notification.create(notifiable: self, created_by: user, action: :approved).
      deliver
  end

  def reproved_by(user)
    reproved!
    Notification.create(notifiable: self, created_by: user, action: :reproved).
      deliver
  end

  def done_by(user)
    done!
    update(resolved_at: DateTime.current)
    Notification.create(notifiable: self, created_by: user, action: :done).
      deliver
  end

  def cancelled_by(user, reason)
    unless reason.nil? || reason.empty?
      update(cancel_reason: reason)
      self.canceled!
      Notification.create(notifiable: self, created_by: user, action: :canceled).
        deliver
    end
  end
end

app/controllers/channels/members_controller.rb
class Channels::MembersController < ApplicationController
  before_action :set_channel
  before_action :set_user, only: [:create]
  respond_to :json

  def create
    @channel_member = @channel.new_member(@user)
    respond_with(@channel, member: @user)
  end

  def destroy
    ChannelMember.destroy params[:id]
  end

  private

    def set_channel
      @channel = Channel.find params[:channel_id]
    end

    def set_user
      @user = User.find params[:user_id]
    end
end

app/controllers/channels/tickets_controller.rb
class Channels::TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy,
                                    :approve, :reprove, :done, :cancel]
  before_action :set_channel
  after_action :verify_authorized, except: [:show, :new_comment]
  respond_to :html, :json

  # GET /tickets
  def index
    authorize @channel, :show?
    @tickets = TicketPolicy::Scope.new(current_user, @channel.tickets).
      resolve.
      default_search(params[:search], params[:status]).
      page(params[:page]).per(params[:per] || 200)
    respond_with(@channel, @tickets)
  end

  # GET /tickets/1
  def show
    authorize @ticket, :show?

    if @ticket.unread? and !current_user.client?
      @ticket.in_progress!
      @ticket.update attended_at: DateTime.current
    end
    respond_with(@channel, @ticket)
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
    authorize @ticket
    respond_with(@channel, @ticket)
  end

  # GET /tickets/1/edit
  def edit
    authorize @ticket
    respond_with(@channel, @ticket)
  end

  # POST /tickets
  def create
    authorize Ticket
    @ticket = Ticket.new(ticket_params)
    @ticket.channel = @channel
    @ticket.created_by = current_user
    if @ticket.save
      Notification.create(notifiable: @ticket, created_by: current_user,
                          action: :created).deliver
    end
    respond_with(@channel, @ticket)
  end

  # PATCH/PUT /tickets/1
  def update
    authorize @ticket
    @ticket.update(ticket_params)
    respond_with(@channel, @ticket)
  end

  # DELETE /tickets/1
  def destroy
    authorize @ticket
    @ticket.destroy
    respond_with(@channel, @ticket)
  end

  def approve
    authorize @ticket
    if @ticket.approved_by(current_user)
      head 204
    else
      render json: I18n.t('notification.server.internal_error').to_json, status: :internal_server_error
    end
  end

  def reprove
    authorize @ticket
    if @ticket.reproved_by(current_user)
      head 204
    else
      render json: I18n.t('notification.server.internal_error').to_json, status: :internal_server_error
    end
  end

  def done
    authorize @ticket
    if @ticket.done_by(current_user)
      head 204
    else
      render json: I18n.t('notification.server.internal_error').to_json, status: :internal_server_error
    end
  end

  def cancel
    authorize @ticket
    if @ticket.cancelled_by(current_user, params[:reason])
      head 204
    else
      render json: I18n.t('notifications.ticket.errors.cancel').to_json, status: :unprocessable_entity
    end
  end

  def new_comment
    @ticket = Ticket.find(params[:ticket_id])
    if @ticket.update(params_new_comment)
      send_comment_notification
    end

    redirect_to channel_ticket_path(channel_id: @channel, id: @ticket)
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def set_channel
    @channel = Channel.find params[:channel_id]
  end

  def send_comment_notification
    emails = if @ticket.comments.last.author.client?
      User.attendant.pluck(:email)
    else
      [@ticket.created_by.email]
    end
    CommentNotificationMailer.notify(emails, @ticket.comments.last).deliver
  end

  # Only allow a trusted parameter "white list" through.
  def ticket_params
    params.require(:ticket).permit(:subject, :content, :is_priority,
                                   :estimated_time, :assign_to_id, :complexity, :attachment)
  end

  def params_new_comment
    params.require(:ticket).permit(comments_attributes: [:content, :attachment]).tap do |whitelisted|
      whitelisted[:comments_attributes]['0'][:author_id] = current_user.id
    end
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  # GET /channels
  def index
    @channels = Channel.all
    authorize(@channels)
    respond_with(@channels)
  end

  # GET /channels/1
  def show
    authorize(@channel)
    respond_with(@channel)
  end

  # GET /channels/new
  def new
    @channel = Channel.new
    authorize(@channel)
    respond_with(@channel)
  end

  # GET /channels/1/edit
  def edit
    authorize(@channel)
    respond_with(@channel)
  end

  # POST /channels
  def create
    @channel = Channel.new(channel_params)
    authorize(@channel)

    @channel.save
    respond_with(@channel) do |format|
      if @channel.persisted?
        format.html { redirect_to channel_tickets_path(@channel) }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /channels/1
  def update
    authorize(@channel)
    @channel.update(channel_params)
    respond_with(@channel)
  end

  # DELETE /channels/1
  def destroy
    @channel.destroy
    authorize(@channel)
    respond_with(@channel)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def channel_params
      params.require(:channel).permit(:name, :purpose, member_ids: [])
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  respond_to :json

  def index
    @tickets = Ticket.all
    respond_with(@tickets)
  end

  def assign_to
    if not current_user.client?
      @ticket = Ticket.find(params[:id])
      @ticket.update(params_ticket)
      Notification.create(notifiable: @ticket, created_by: current_user, action: :assigned).
        deliver

      render json: { assign_to: @ticket.assign_to.email }.to_json
    else
      render json: 'Unauthorized', status: 403
    end
  end

  def download
    @ticket = Ticket.find(params[:id])
    authorize @ticket, :download?
    redirect_to @ticket.attachment.expiring_url(10)
  end

  private

  def params_ticket
    { assign_to_id: params[:attendant_id] }
  end
end

app/views/channels/tickets/_comments.html.erb
<% unless @ticket.comments.empty? and (@ticket.approved? or @ticket.canceled?)%>
  <div class="row">
    <div class="col-sm-12">
      <h3><%= t('comment.headings.main') %></h3>
    </div>
  </div>
<% end %>

<% unless @ticket.approved? or @ticket.canceled? %>
  <div class="row">
    <%= form_for @ticket, url: channel_ticket_new_comment_path(@channel, @ticket),
      method: :post, role: :form, data: { dropzone: true }, id: 'new-comment' do |f| %>
      <%= f.fields_for :comments, @ticket.comments.build do |t| %>
        <div class="col-sm-12">
          <div class="form-group">
            <%= t.text_area :content, class: 'form-control', rows: 6 %>
            <div class="comment_dropzone dropzone-previews hidden">
              <p class="dz-message">Solte um arquivo aqui para anexar.</p>
            </div>
            <div class="fallback">
              <%= t.file_field :attachment, class: 'form-control', rows: 6 %>
            </div>
          </div>
          <%= f.submit t('comment.new.button'), class: 'btn btn-primary pull-right', id: 'comment_submit' %>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

<div class="comments">
  <% @ticket.comments.recently_first.each do |comment| %>
    <div class="comment">
      <div class="img">
        <%= image_tag comment.author.avatar.url(:square), class: 'img-circle thumb' %>
      </div>
      <div class="box">
        <div class="info">
          <div class="author <%= comment.author.user_type %>">
            <strong><%= comment.author.email %></strong>
          </div>
          <div class="date" title="<%= l comment.created_at %>">
            <%= l comment.created_at, format: :default %>
          </div>
        </div>
        <div class="content">
          <%= simple_format comment.content %>

          <% if comment.attachment.present? %>
            <div class="row">
              <div class="col-sm-6">
                <label><%= Ticket.human_attribute_name(:attachment) %>: </label>
                <%= link_to comment.attachment_file_name, comment_attachment_download_path(comment), 'target'=>'_blank' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/channels/tickets/_form.html.erb
<%= form_for([@channel, @ticket], role: :form) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :subject, class: "form-control subject-field", placeholder: t('helpers.ticket.subject') %>
  </div>
  <hr>
  <div class="form-group">
    <%= f.text_area :content, class: "form-control", rows: 10, placeholder: t('helpers.ticket.content') %>
  </div>

  <div class="form-group">
    <div class="checkbox">
      <%= f.label :is_priority do %>
        <%= f.check_box :is_priority, class: "checkbox" %>
        <%= Ticket.human_attribute_name(:is_priority) %>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :attachment %>
    <%= f.file_field :attachment %>
  </div>

  <div class="form-group">
    <%= f.submit value: t('links.ticket.save'), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/channels/tickets/_popovers.html.erb
<% unless current_user.client? %>
  <!-- Popovers -->
  <template id="estimated-time-popover">
    <div class="ticket-popovers">
      <%= form_for [@channel, @ticket], remote: true, data: { "reverse-id"=>"#estimated-time-popover" } do |f| %>
        <%= hidden_field_tag :format, :json %>
        <div class="form-group">
          <%= f.range_field :estimated_time, max: 100, min: 1, step: 6 %>
        </div>
        <%= f.submit value: t('links.save'), class: "btn btn-default btn-sm",
          "data-loading-text"=>t('loading') %>
      <% end %>
    </div>
  </template>
  <template id="assign-to-popover">

    <div class="ticket-popovers">
      <%= form_tag(assign_to_ticket_path(@ticket), { id: 'assign-to', method: :post, remote: true, 'data-type' => 'json', :'data-type' => 'json'}) do %>
        <%= hidden_field_tag :format, :json %>
        <div class="form-group">
          <%= select_tag :attendant_id, options_from_collection_for_select(User.attendant, "id", "email", @ticket.assign_to_id) %>
        </div>
        <%= submit_tag '', value: t('links.save'), class: "btn btn-default btn-sm", "data-loading-text"=>t('loading'), data: { 'behaviour' => 'assign-to' } %>
      <% end %>
    </div>
  </template>

  <template id="complexity-popover">
    <div class="ticket-popovers">
    <%= form_for [@channel, @ticket], remote: true, data: { "reverse-id"=>"#complexity-popover" } do |f| %>
      <%= hidden_field_tag :format, :json %>
      <div class="form-group">
        <%= f.range_field :complexity, max: 3, min: 1 %>
      </div>
      <%= f.submit value: t('links.save'), class: "btn btn-default btn-sm",
        "data-loading-text"=>t('loading') %>
    <% end %>
    </div>
  </template>
  <% end %>
  
  <% if policy(@ticket).cancel? %>
  <template id="cancel-popover">
    <div class="ticket-popovers">
    <%= form_tag channel_tickets_cancel_path(@channel, @ticket),
      remote: true, method: :PUT, data: { "reverse-id"=>"#cancel-popover" } do %>
      <%= hidden_field_tag :format, :json %>
      <div class="form-group">
        <%= text_area_tag :reason, '', class: 'form-control' %>
      </div>
      <%= submit_tag t('links.save'), class: "btn btn-default btn-sm",
        "data-loading-text"=>t('loading') %>
    <% end %>
    </div>
  </template>
<% end %>

app/views/channels/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', [@channel, @ticket] %> |
<%= link_to 'Back', channel_tickets_path(@channel) %>

app/views/channels/tickets/index.html.erb
<div class="statuses-filter">
  <div class="pull-right">
    <span><%= link_to t('links.ticket.open'), channel_tickets_path(@channel, params.except(:status)) %></span>
    <span><%= link_to t('links.ticket.approved'), channel_tickets_path(@channel, params.merge(status: :approved)) %></span>
    <span><%= link_to t('links.ticket.cancelled'), channel_tickets_path(@channel, params.merge(status: :canceled)) %></span>
  </div>
</div>

<h1>#<%= @channel.name %></h1>
<% if policy(Ticket).new? %>
  <%= link_to t('links.ticket.new'), new_channel_ticket_path(@channel) %>
<% end %>

<div class="clear"></div>
<div class="tickets">
<% if @tickets.empty? %>
  <p><em><%= t('ticket.messages.none') %></em></p>
<% end %>
<% @tickets.apply_sort.each do |ticket| %>
  <%= render 'tickets/item', ticket: ticket %>
<% end %>
</div>

<%= paginate @tickets %>

app/views/channels/tickets/new.html.erb
<h1><%= t('ticket.new.headings.main') %></h1>

<%= render 'form' %>

app/views/channels/tickets/show.html.erb
<div class="ticket-page">
  <div class="row">
    <div class="col-sm-8">
      <div class="row">
        <div class="col-sm-12">
          <%= link_to 'Voltar para a página de tickets', channel_tickets_path(@ticket.channel) %>
          <h2>
            #<%= @ticket.id %> - <%= @ticket.subject %>
          </h2>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <%= simple_format @ticket.content %>
        </div>
      </div>

      <% unless current_user.client? %>
        <div class="row">
          <div class="col-sm-4">
            <label><%= Ticket.human_attribute_name(:estimated_time) %>: </label>
            <a data-toggle="popover"
              data-html="true"
              data-placement="bottom"
              data-success-use="estimated_time"
              title="<%= Ticket.human_attribute_name(:estimated_time) %>"
              data-content-target="#estimated-time-popover">
              <%= @ticket.estimated_time || t('not_defined') %>
            </a>
          </div>
          <div class="col-sm-4">
            <label><%= Ticket.human_attribute_name(:assign_to) %>: </label>
            <a
              id="assign-to-target"
              data-toggle="popover"
              data-html="true"
              data-placement="bottom"
              data-success-use="assign_to"
              title="<%= Ticket.human_attribute_name(:assign_to) %>"
              data-content-target="#assign-to-popover">
              <% if @ticket.assign_to_id %>
                <%= @ticket.assign_to.email %>
              <% else %>
                <%= t('not_defined') %>
              <% end %>
            </a>
          </div>
          <div class="col-sm-4">
            <label><%= Ticket.human_attribute_name(:complexity) %>: </label>
            <a data-toggle="popover"
              data-html="true"
              data-placement="bottom"
              data-success-use="complexity"
              title="<%= Ticket.human_attribute_name(:complexity) %>"
              data-content-target="#complexity-popover">
              <%= @ticket.complexity || t('not_defined') %>
            </a>
          </div>
        </div>
      <% end %>

      <% if @ticket.attachment.present? %>
      <div class="row">
        <div class="col-sm-6">
          <label><%= Ticket.human_attribute_name(:attachment) %>: </label>
          <%= link_to @ticket.attachment_file_name, ticket_attachment_download_path(@ticket), 'target'=>'_blank' %>
        </div>
      </div>
      <% end %>

      <%= render 'comments' %>
    </div>

    <div class="col-sm-4 ticket-sidebar">
      <% unless @ticket.unread? %>
        <div class="row">
          <div class="col-sm-12">
            <center>
              <% if @ticket.is_priority %>
                <%= image_tag "stamps/important.png", class: "stamp img-circle" %>
              <% end %>
              <%= image_tag "stamps/#{@ticket.status}.png", class: "stamp", title: (@ticket.cancel_reason if @ticket.canceled?) %>
            </center>
          </div>
        </div>
      <% end %>
      <div class="row">
        <div class="col-sm-2">
          <%= content_tag :span, title: @ticket.created_by.try(:email) do %>
            <%= image_tag @ticket.created_by.avatar(:thumb), class: 'img-circle thumb' %>
          <% end %>
        </div>
        <div class="col-sm-10">
          <%= @ticket.created_by.email %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-11 col-sla">
          <center>
            <ul>
              <li><%= complexity_image(@ticket, self) %></li>
              <% resolution_sla(@ticket) do |icon| %>
                <li><%= icon %></li>
              <% end %>
            </ul>
          </center>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <center>
          <hr />
          <div class="actions">
            <% if policy(@ticket).done? %>
              <%= link_to t('links.ticket.done'), channel_tickets_done_path(@channel, @ticket),
                remote: true, method: :PUT, class: 'btn btn-info',
                data: { "loading-text"=>t('loading'), "complete-text"=>t('success') } %>
            <% end %>
            <% if policy(@ticket).approve? %>
              <%= link_to t('links.ticket.approve'), channel_tickets_approve_path(@channel, @ticket),
                remote: true, method: :PUT, class: 'btn btn-success',
                data: { "loading-text"=>t('loading'), "complete-text"=>t('success'),
                  "data-toggle"=>"button" } %>
            <% end %>
            <% if policy(@ticket).reprove? %>
              <%= link_to t('links.ticket.reprove'), channel_tickets_reprove_path(@channel, @ticket),
                remote: true, method: :PUT, class: 'btn btn-danger',
                data: { "loading-text"=>t('loading'), "complete-text"=>t('success'),
                  "data-toggle"=>"button" } %>
            <% end %>
            <% if policy(@ticket).cancel? %>
              <a class="link-danger" data-toggle="popover"
                data-html="true"
                data-placement="bottom"
                title="<%= t('links.ticket.cancel') %>"
                data-complete-text="<%= t('success') %>"
                data-loading-text="<%= t('loading') %>"
                data-content-target="#cancel-popover">
                <%= t('links.ticket.cancel') %>
              </a>
            <% end %>
          </div>
          </center>
        </div>
      </div>
    </div>
  </div>

  <%= render 'popovers' %>

</div>