config/routes.rb
Rails.application.routes.draw do

  unauthenticated do
    devise_scope :user do
      root to: "devise/sessions#new", :as => 'unauthenticated_user_root'
    end
  end

  devise_for :users, controllers: { registrations: "users/registrations" }

  patch "users/accept_invite"=>"users#accept_invite", as: :accept_invite

  authenticate :user do
    root to: "dashboards#show", :as => 'authenticated_user_root'

    resources :invitations, only: [:new, :create]

    get 'profile'=>'profiles#edit', as: :myprofile
    patch 'profile'=>'profiles#update'

    get 'metrics'=>'metrics#show', as: :metrics
    resources :users, only: [:index]

    resources :channels, only: [:update, :create, :destroy] do
      resources :tickets, module: 'channels' do
        post 'new_comment'
      end

      namespace :tickets, module: 'channels' do
        put ':id/approve'=>'tickets#approve', as: :approve
        put ':id/reprove'=>'tickets#reprove', as: :reprove
        put ':id/done'=>'tickets#done', as: :done
        put ':id/cancel'=>'tickets#cancel', as: :cancel
      end

      resources :members, defaults: { format: :json }, only: [:create, :destroy], module: 'channels'
    end

    resources :tickets, only: [] do
      post :assign_to, on: :member
    end

    get 'tickets/:id/download'=>'tickets#download', as: :ticket_attachment_download
    get 'comments/:id/download'=>'comments#download', as: :comment_attachment_download

    resources :groups, only: [:new, :create, :show] do
      member do
        post 'add_user'
        delete 'inactivate_member'
        post 'add_channel'
      end
    end

    resource :dashboard, only: [:show]
  end

  if Rails.env.development?
    mount MailPreview => 'mail_preview'
  end
end

app/views/layouts/_analytics.html.erb
<% if ENV["SEGMENT_IO_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.io/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_IO_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/layouts/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% flash.each do |key, value| -%>
      <div role="alert" class="alert <%= bootstrap_class_for key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12">
        <div class="pull-right tracer">
          Tracersoft 2014 <%= icon :code %>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "layouts/analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/layouts/_nav.html.erb
<div class="navbar navbar-fixed-top menu" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><%= icon :code %> Suporte!</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle"
             data-toggle="dropdown"
             href="#">
              <%= current_user.email %>
              <b class="caret"></b>
            </a>
          <ul class="dropdown-menu">
            <li><%= link_to t('links.profile'), myprofile_path %></li>
            <% if current_user.client? %>
              <li><%= link_to t('invitation.link.client'), new_invitation_path %></li>
            <% else %>
              <li><%= link_to t('invitation.link.attendant'), new_invitation_path %></li>
            <% end %>
            <li><%= link_to t('metrics'), metrics_path %></li>
            <li><%= link_to t('link.sign_out'), destroy_user_session_path,
              method: :delete %></li>
          </ul>
        </li>
        <li><%= link_to icon('question-circle'),
          'https://s3-sa-east-1.amazonaws.com/suporte.tracersoft.com.br/assets/Tutorial.pdf',
          target: '_blank' %></li>
      </ul>

      <% if @channel.present? and @channel.persisted? %>
        <div class="navbar-form navbar-right">
        <%= form_tag channel_tickets_path(@channel, params), method: :get do %>
          <%= hidden_field_tag :status, params[:status] %>
          <%= text_field_tag :search, params[:search], class: "form-control", placeholder: t(:search) %>
        <% end %>
         </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_public_nav.html.erb
<div class="navbar navbar-fixed-top menu" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= icon :code %> Suporte!</a>
    </div>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div>
  <h4><%= t :channels %></h4>
  <ul class="nav nav-sidebar channels">
      <% channels.each do |channel| %>
        <%= content_tag :li, class: ('active' if active_channel?(channel)) do %>
          <%= link_to channel_tickets_path(channel), class: 'channel' do %>
            <span class="truncate channel-name">
              <span class="prefix">#</span> <%= channel.name %>
          </span>
          <% if channel_has_notification?(channel) %>
            <span class="badge alert-info pull-right">
              <%= channel_notification_number(channel) %>
            </span>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </ul>

  <% if policy(Channel).new? %>
    <div class="action">
    <a id="create-channel"
      data-html="true"
      data-toggle="popover"
      data-title="<%= t('links.channel.new') %>"
      data-content-target="#new-channel-popover">
      <%= t('links.channel.new') %>
    </a>
    </div>

    <template id="new-channel-popover">
      <%= form_for(Channel.new) do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, required: true, class: 'form-control'  %>
        </div>
        <div class="form-group">
          <%= f.label :purpose %>
          <%= f.text_area :purpose, class: 'form-control' %>
        </div>
        <div class="actions">
          <%= f.submit t('links.save'), class: 'btn btn-primary' %>
        </div>
      <% end %>
    </template>
  <% end %>

  <% if policy(Group).index? %>
    <h4><%= t :groups %></h4>
    <ul class="nav nav-sidebar groups">
      <% Group.all.each do |group| %>
        <li><%= link_to group.name, group, class: 'group truncate' %></li>
      <% end %>
    </ul>
  <% end %>

  <% if policy(Group).new? %>
    <div class="action">
    <a id="create-group"
      data-html="true"
      data-toggle="popover"
      data-title="<%= t('links.group.new') %>"
      data-content-target="#new-group-popover">
      <%= t('links.group.new') %>
    </a>
    </div>

    <template id="new-group-popover">
      <%= form_for(Group.new) do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, required: true, class: 'form-control'  %>
        </div>
        <div class="form-group">
          <%= f.label :purpose %>
          <%= f.text_area :purpose, class: 'form-control' %>
        </div>
        <div class="actions">
          <%= f.submit t('links.save'), class: 'btn btn-primary' %>
        </div>
      <% end %>
    </template>
  <% end %>
</div>

app/views/layouts/application.html.erb
<%= content_for :body do %>
  <%= render "layouts/nav" -%>

  <div id="main" class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-md-2 col-lg-2 sidebar">
        <%= render "layouts/sidebar" -%>
      </div>
      <div class="col-sm-9 col-md-10 col-lg-10">
        <%= render "layouts/flashes" -%>
        <%= yield %>
      </div>
    </div>
  </div>
<% end %>
<%= render template: "layouts/base" %>

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <title>Suporte</title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= render "layouts/javascript" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <div id="wrap">
    <%= content_for?(:body) ? yield(:body) : yield %>
    <div class="clear"></div>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/login.html.erb
<%= content_for :body do %>
  <%= render "layouts/public_nav" -%>

  <div class="container">
    <div class="row">
      <div class="col-sm-4 col-sm-offset-4 col-xs-12">
        <div class="login-box">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
<% end %>
<%= render template: "layouts/base" %>

app/views/layouts/notification.html.erb
<div>
<table style="width: 100%;
    background-color: #f8f7f5;
    padding: 80px;
    font-family: Helvetica, Arial;">
  <tr>
    <td align="center" valign="top">
      <table style="width: 800px;
    border: 1px solid #dfdfda;
    background-color: #fffffe;
    border-radius: 6px;">
        <tr>
          <td style="font-size: 20px;
    font-weight: 500;
    background-color: #2c3e50;
    padding: 12px;
    color: white;
    border-radius: 4px;">Suporte!</td>
        </tr>
        <tr>
          <td>
            <table style="height: 400px;
    width: 100%;
    padding: 20px;">
              <tr style="height: 100px; font-size: 24px">
                <% if content_for?(:img) %>
                  <td style="width: 120px;"><%= yield :img %></td>
                <% end %>
                <td><%= yield :subject %></td>
              </tr>
              <tr style="height: 2px"><td colspan="2" style="padding-top: 20px"><hr style=" border: 0;
    height: 0;
    border-top: 1px solid rgba(0, 0, 0, 0.1);
    border-bottom: 1px solid rgba(255, 255, 255, 0.3);" /></tr>
              <tr>
                <td colspan="2" style="vertical-align: top;">
                  <center><%= yield %></center>
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr>
          <td style="font-size: 10px; padding: 10px; background-color: #2c3e50; color: white;
    border-radius: 4px;">Tracersoft - 2014</td>
        </tr>
      </table>
    </td>
  </tr>
</table>
</div>